### ISSUE TITLE
Сумашедшие кавычки =)

### ISSUE THREAD

**Issue by stcoder** [typograf/typograf#100]
Типограф не правильно расставляет кавычки

Прикрепляю скрин
![skitch](https://cloud.githubusercontent.com/assets/1697524/7531629/5d66fe86-f576-11e4-9792-c32a43a993b7.png)

И [ссылка](http://ekburg.tv/novosti/gorod/uralskij_tadzhik_prezentoval_svoju_novuju_knigu_o_ekaterinburge)

P.S. Типограф очень крутой, спасибо вам! =)

**Comment by hcodes** [comment]
Посмотрел оттипографированный текст с настройками по умолчанию, ошибок не нашёл.
А какие правила включены или отключены?

**Comment by stcoder** [comment]
typograf.enable('ru/optalign/*');
typograf.disable('ru/dash/to');

**Comment by hcodes** [comment]
Проверил на https://typograf.github.io - ошибок не нашёл.

А какая версия используется?
Может надо весь текст статьи типографить?

**Comment by Zlokazov** [comment]
Присоединяюсь к реквесту! Крутой типограф, очень ждем фикс. Вроде как проблема воспоизводится не только из-за тегов курсива, еще из-за тегов strong, b (полужирности), a (гиперссылки)

**Comment by hcodes** [comment]
Да, начал разбираться и нашёл много интересного...
Возникает проблема с расстановкой кавычек при наличии любых тегов.
Например, такие случаи:
```
<p>"Какой-то текст"</p> // Всё ок

"<a href-="/">Какая-то ссылка</a>" // Проблема

<p>"<i>Какой-то текст</i>"</p> // Проблема 

<div class="t"><p>"<i>Какой-то текст<a href="/">link</a></i>"</p></div>  // Большая проблема

```
По соседним символам у кавычки нельзя понять, что она открывающая.

**Comment by hcodes** [comment]
Поправил, v2.11.1.

В сложных случаях кавычки могут расставляться некорректно.
```<div class="t"><p>"<i>Какой-то текст<a href="/">link</a></i>"</p></div>```

Буду фиксить это отдельно.
