### ISSUE TITLE
Не верная расстановка кавычек при вложенности

### ISSUE THREAD

**Issue by drzl** [typograf/typograf#106]
"Иннопром". "Синий "мужчина" знак". -> „Иннопром“. «Синий „мужчина“ знак».
Наверное должно быть так -> «Иннопром». «Синий „мужчина“ знак».

От текущего поведения страдает вся расстановка кавычек выше места со вложенностью.

**Comment by hcodes** [comment]
Спасибо, это баг, поправлю.

**Comment by drzl** [comment]
Вдруг актуально: википедевский типограф адекватно расставил кавычки https://ru.wikipedia.org/w/index.php?title=MediaWiki:Wikificator.js&action=raw&ctype=text/javascript

**Comment by hcodes** [comment]
Актуально, посмотрю...

**Comment by hcodes** [comment]
Исправления появятся в версии 2.13.0.
Заодно сделал поддержку кавычек третьего уровня.
