### ISSUE TITLE
Прямая речь в начале строки

### ISSUE THREAD

**Issue by drzl** [typograf/typograf#107]
"- Превед, медвед."
Не обрабатывается, оставляет минус.

**Comment by hcodes** [comment]
После кавычки в прямой речи тире не ставится.
http://www.gramota.ru/spravka/rules/?rub=znapr

**Comment by drzl** [comment]
Кавычки в моём сообщении экранируют тире т. к. редактор гитхаба заменяет его на булет.
Вот правильный способ:
\- Превед, медвед

**Comment by hcodes** [comment]
Тире ставится.
https://typograf.github.io/#!text=-%20%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82%20%D0%BC%D0%B5%D0%B4%D0%B2%D0%B5%D0%B4

**Comment by hcodes** [comment]
Может выбран английский язык?

**Comment by drzl** [comment]
При внимательном рассмотрении я обнаружил теги перед тире:
https://typograf.github.io/#!text=%3Cp%3E-%20%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82%20%D0%BC%D0%B5%D0%B4%D0%B2%D0%B5%D0%B4%3C%2Fp%3E%0A%3Cp%3E-%20%D0%B2%20%D0%B0%D1%8B%D0%B2%20%D0%B0%D1%8B%D0%B2%20%D0%B0%D1%8B%3C%2Fp%3E%0A%3Cp%3E-%20%D0%B2%20%D1%8B%D0%B0%20%D0%B0%D1%8B%D0%B2%D0%B0%20%D1%8B%D0%B2%D0%B0%20%D1%8B%D0%B2%3C%2Fp%3E%0A

**Comment by hcodes** [comment]
Хорошо,  добавлю для тире в условие теги.
