### ISSUE TITLE
Опция: заменять лишние неразрывные пробелы на обычные пробелы

### ISSUE THREAD

**Issue by vernikr** [typograf/typograf#133]
Кейс:
1. Пользователь написал комментарий: "Как чудесен я".
2. Типограф справедливо поставил перед "я" неразрывный пробел:
   ![image](https://cloud.githubusercontent.com/assets/14224999/9801564/99c77cee-581c-11e5-9560-2c1749203a13.png)
3. Пользователь отправил комментарий.
4. Теперь пользователь хочет отредактировать комментарий. Он подгружается в поле ввода со всеми спец-символами). Пользователь помещает курсор перед словом "я" и вставляет текст "обычно ".
5. Типограф снова справедливо поставил перед "я" неразрывный пробел, но старый неразрывный пробел (после "чудесен") по-прежнему в наличии, хотя не обоснован:

![image](https://cloud.githubusercontent.com/assets/14224999/9801635/f4b946e6-581c-11e5-9c83-2a14a6d93e5a.png)

Поэтому, думаю, хорошо было бы иметь опцию, которая конвертировала бы неразрывные пробелы, которые не обоснованы ни одним из активный правил, в обычные пробелы.

**Comment by hcodes** [comment]
Да, интересный случай. По-хорошему, типограф должен править ошибки с неправильно расставленными пробелами.
Наверное, при типографировании на лету нужно насильно заменять неразрывные пробелы на обычные.

**Comment by vernikr** [comment]
Возможно. Но есть риск потерять неразрывные пробелы, которые пользователь вручную поставил в тексте (например, в фразе "MS Windows" — где алгоритму трудно догадаться), если данный пробел не может быть восстановлен текущими правилами типографа. Поэтому я предложил опцию.

Случай, конечно, редкий и больше относится не к пользователям, а к редакторам сайта. Возможно, опцию "править ошибки с неправильно расставленными пробелами" стоит держать включенной по умолчанию.

**Comment by hcodes** [comment]
Для данного правила можно ввести дополнительное поле `live: true`. Правило будет работать только при типографировании на лету. Ну и ввести отдельный режим типографирования на лету.

**Comment by vernikr** [comment]
Наверное, да.

**Comment by hcodes** [comment]
v3.3.0

**Comment by vernikr** [comment]
Спасибо.
