### ISSUE TITLE
Добавить правило для апострофа

### ISSUE THREAD

**Issue by hcodes** [typograf/typograf#136]

**Comment by zuf** [comment]
Это, я так понимаю, чтобы не было так?

```
Bob’s --> Bob«s
```

Очень бы хотелось такие случаи исправить.

**Comment by hcodes** [comment]
Да.

**Comment by hcodes** [comment]
v3.5.0

**Comment by mrnix** [comment]
Спасибо за фикс, очень спасло. 
Но другая проблема возникла при парсинге двух апострофов в строке:
`Them’s Fightin’ Herds` -> `Themʼs Fightin« Herds`

**Comment by hcodes** [comment]
Правило сделал только для русского языка. Попробую ещё раз переписать расстановку кавычек, учитывая этот случай. Там также есть проблема с дюймами и секундами.

**Comment by hcodes** [comment]
#143
