### ISSUE TITLE
Неразрывный пробел перед последним коротким словом

### ISSUE THREAD

**Issue by vernikr** [typograf/typograf#140]
(Не претендую на грамотное и полноценное описание логики. Это скорее черновик.)

Сейчас данное правило работает только, если после слова стоят знаки .,?!:;

Думаю правило должно также срабатывать, если после слова (везде далее идет речь о пробеле перед "5"):
1. Ничего не стоит (например, если пользователь написал текст заголовка):
   **Сегодня я получил 5**
2. Начинается новая строка:
   **Сегодня я получил 5
   И дальше продолжаю стих**
3. Стоит какой-то содержательный символ, а после него — бессодержательный (пробел любого вида, перенос любого вида, новая строка, пустота и что там ещё бывает). Например:
   **Сегодня я рад (получил 5)
   Сегодня я получил 5+
   или 5-
   или 5–
   или 5%
   Сегодня диагональ равна 5"
   Пять секунд некоторые пишут в виде 5'**
## 

4: Другой момент: сейчас перед коротким словом не ставится неразрывный пробел, если слово начинается не с буквы (даже со знаками .,?!:; после слова):
**Сегодня я получил 5. И очень рад.**

**Comment by hcodes** [comment]
1. Лучше сделать отдельное правило, т. к. у чисел точки и запятые могут быть разделителями плавающей части.
2. Надо доработать.
3. Надо доработать.
4. Надо доработать.

**Comment by vernikr** [comment]
1. Не уверен что правильно понял... Я посчитал, что 5,1 это уже длинное слово согласно текущим правилам программы, потому что содержит 3 символа. Т.е. перед ним наверное не нужно ставить неразрывный пробел.

Тут, кстати, всплывает следующий пункт:

5: Не думали об идее сделать настройку того, что такое короткое слово? Сколько в нем должно быть символов и в каком контексте оно должно находится. Например, висячее слово из 4 букв в конце абзаца может вполне считаться коротким.

**Comment by hcodes** [comment]
1. Решается настройкой длины цифры. 

```
1 3.1 5% 25% 5,5%.
```
1. Кажется, пользователю проще будет своё правило написать, чем настраивать короткое слово.
   Потому что настройка будет регулярным выражением, которое потом нужно будет добавить к другому выражению.

**Comment by vernikr** [comment]
ОК, понял.

**Comment by hcodes** [comment]
Добавил новое правило `common/nbsp/beforeShortLastNumber`.
В следующей версии Типографа будет доступно.
