### ISSUE TITLE
Учесть апостроф при расстановке кавычек

### ISSUE THREAD

**Issue by hcodes** [typograf/typograf#143]

**Comment by hcodes** [comment]
`Them’s Fightin’ Herds`

**Comment by ai** [comment]
Привет. Крутой проект, мы внедрили его в Амплифер. Но отсутствие логики апострофа — сильно мешает.

Если нужна помощь, объясни примерно что и где исправить — я пошлю туда людей с Cult of Martians.

**Comment by hcodes** [comment]
Апостроф затрагивает правило с кавычками. Нужно собрать все случаи с апострофами и ещё раз пересмотреть расстановку кавычек. На каникулах постараюсь посмотреть данное issue.

**Comment by ai** [comment]
Пиши, если будет нужна помощь. Но я обычно использую примерно подобный алгоритм `\w'[dsDS]`.

**Comment by hcodes** [comment]
Дюймы вынес в отдельную задачу #211.

**Comment by hcodes** [comment]
v5.8.0
