### ISSUE TITLE
Знак валюты и разрядка чисел ($22 000 => 22 $ 000)

### ISSUE THREAD

**Issue by mrnix** [typograf/typograf#144]
Привет!
Нашел интересный баг:
`YouTube-блогер попросил $22 000 за обзор игры` 
типографится в 
`YouTube-блогер попросил 22&nbsp;$ 000&nbsp;за&nbsp;обзор игры`

**Comment by hcodes** [comment]
Да, такой случай [не учтён](https://github.com/typograf/typograf/blob/dev/src/rules/ru/money/dollar.js).
Поправлю и добавлю в тесты.

**Comment by hcodes** [comment]
v4.0.0

**Comment by mrnix** [comment]
Проблема осталась:

``` javascript
var typograf = new Typograf({ lang: 'ru' });
typograf.execute('YouTube-блогер попросил $22 000 за обзор игры ')
// "YouTube-блогер попросил 22 $ 000 за обзор игры" 
```

**Comment by hcodes** [comment]
Фикс сделал, правки будут в версии 4.0.1.

**Comment by hcodes** [comment]
Выпустил v4.0.1.

**Comment by mrnix** [comment]
круто, спасибо!
