### ISSUE TITLE
Скрывать ссылки при типографировании

### ISSUE THREAD

**Issue by hcodes** [typograf/typograf#151]
Ломает ссылки из-за того же правила, но теперь после вопросительного знака.

`https://www.youtube.com/watch?v=C0DPdy98e4c` 
=>
`https://www.youtube.com/watch? v=C0DPdy98e4c`

Также ломает даты в ссылках из-за [ru/date/fromISO](https://github.com/typograf/typograf/blob/dev/src/rules/ru/date/fromISO.js).

`https://lenta.ru/news/2016/04/12/notes/`
=>
`https://lenta.ru/news/12.04.2016/notes/`

**Comment by lgordey** [comment]
Может быть можно заигнорить ссылки для всех правил типографа?

Мне кажется это как раз тот случай, который типограф должен обходить стороной. 
И мб архитектурно было бы лучше exclude'ить ссылки на начальном этапе, чем править регулярки в каждом конкретном правиле.

**Comment by hcodes** [comment]
Да, надо так и сделать.

**Comment by hcodes** [comment]
v5.3.0
