### ISSUE TITLE
Отключить всё кроме ...

### ISSUE THREAD

**Issue by anorudes** [typograf/typograf#152]
Ребята, подскажите,  как можно реализовать следующее:
tp.disable('_');
tp.enable('ru/optalign/_');

Отключить все правила, но включить пунктуацию. К сожалению, так не работает

**Comment by lgordey** [comment]
Отключать надо через звездочку:

``` javascript
tp.disable('*');
```

**Comment by hcodes** [comment]
Да, через звёздочку.

**Comment by anorudes** [comment]
Это я скопировал коряво, звездочку юзал. Проблема оказалось в том, что правило ru/optalign не то, что я думал делало. Спасибо за быстрый ответ)
