### ISSUE TITLE
Неразрывные пробелы / textare / FireFox

### ISSUE THREAD

**Issue by EarthDweller** [typograf/typograf#154]
Как вариант, можно заменить textarea справа на Ace редактор (https://ace.c9.io/#nav=about), там не только не убираются неразрывные пробелы в FireFox (и при копировании), но и подсвечиваются... но уже не будут выделятся слова с ошибками, нужно будет отдельно прописывать словарь или проверку.

**Comment by hcodes** [comment]
Ага,  попробую прикрутить.

**Comment by hcodes** [comment]
Прикрутил, размер статики вырос, штатное выделение ошибок пропало. В данном дизайне есть две textarea, если будут вставляться длинные тексты придётся обновлять две ace-textarea, обновление на ввод символов, на мобильных устройствах могут быть тормоза.
Пока не готов менять обычные textarea на Ace.

В будущем, если уйти в интерфейсе от двух textarea на экране можно будет подумать об Ace.
Спасибо за предложение.
