### ISSUE TITLE
Ошибка в обработке аббревиатур

### ISSUE THREAD

**Issue by Dem137** [typograf/typograf#156]
Если в конце предложения стоит аббревиатура из трех букв, при обработке она считается инициалами и вторая буква заменяется на точку.
`с корреспондентом РАН. Читайте в разделе`
`с корреспондентом Р. Н. Читайте в разделе`

https://typograf.github.io/#!text=%0A%D1%81%20%D0%BA%D0%BE%D1%80%D1%80%D0%B5%D1%81%D0%BF%D0%BE%D0%BD%D0%B4%D0%B5%D0%BD%D1%82%D0%BE%D0%BC%20%D0%A0%D0%90%D0%9D.%20%D0%A7%D0%B8%D1%82%D0%B0%D0%B9%D1%82%D0%B5%20%D0%B2%20%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B5

**Comment by hcodes** [comment]
v5.3.1
