### ISSUE TITLE
Отсутствие пробела после кавычки ломает последующие кавычки

### ISSUE THREAD

**Issue by melfa** [typograf/typograf#158]
В тексте ломаются кавычки.
Если перед «в театре» поставить пробел — с кавычками всё будет хорошо. Однако, в длинном тексте, например, редактору статьи найти это место будет не так просто.

Исходный текст:

Из всей нашей культурной программы самое сильное впечатление на меня произвела постановка &quot;Р.Р.Р.&quot; по произведению Достоевского &quot;Преступление и наказание&quot;в театре Моссовета. Она буквально влюбила меня в театр. 
&quot;Мы напихиваем в детей ненужное барахло&quot;. 5 радикальных тезисов Германа Грефа об образовании.

Типографированный текст:

Из всей нашей культурной программы самое сильное впечатление на меня произвела постановка «Р.Р.Р.» по произведению Достоевского «Преступление и наказание„в театре Моссовета. Она буквально влюбила меня в театр.
‚Мы напихиваем в детей ненужное барахло‘. 5 радикальных тезисов Германа Грефа об образовании.

**Comment by melfa** [comment]
https://typograf.github.io/#!text=Из%20всей%20нашей%20культурной%20программы%20самое%20сильное%20впечатление%20на%20меня%20произвела%20постановка%20%26quot%3BР.Р.Р.%26quot%3B%20по%20произведению%20Достоевского%20%26quot%3BПреступление%20и%20наказание%26quot%3Bв%20театре%20Моссовета.%20Она%20буквально%20влюбила%20меня%20в%20театр.%20%0A%26quot%3BМы%20напихиваем%20в%20детей%20ненужное%20барахло%26quot%3B.%205%20радикальных%20тезисов%20Германа%20Грефа%20об%20образовании.

**Comment by hcodes** [comment]
В тексте допущена ошибка, из-за отсутствия пробела ломается логика расстановки кавычек.
Тут могут быть и другие проблемы, например, лишние кавычки, отсутствие закрывающих кавычек и пр.
Возникает вопрос, а должен ли Типограф в этих случаях пытаться расставлять кавычки?

**Comment by kobezzza** [comment]
> Возникает вопрос, а должен ли Типограф в этих случаях пытаться расставлять кавычки?

На мой взгляд - нет. Орфография и типографика - разные задачи и должны использовать разные инструменты.

**Comment by hcodes** [comment]
Для больших текстов нужен diff, постараюсь прикрутить на https://typograf.github.io

**Comment by melfa** [comment]
А не могли бы вы подсказать сценарий использования для сайта, в котором будет какой-то отдельный инструмент, который подскажет что вот тут пробела не хватает? Я не очень понимаю что это должен быть за инструмент.

**Comment by hcodes** [comment]
Добавил [diff-режим](https://typograf.github.io), должен помочь на длинных текстах.
![Пример](https://cloud.githubusercontent.com/assets/157520/15159863/6e4cf452-16ff-11e6-858b-d960205cf894.png)

**Comment by hcodes** [comment]
В идеале, отдельный инструмент должен подчёркивать красным цветом места ошибок. Пока такого инструмента нет, но было бы круто его сделать.

**Comment by hcodes** [comment]
v5.5.1
