### ISSUE TITLE
Не удалять 2 пробела в конце строки, т.к. в маркдауне это переход на новую строку без отбивки абзаца

### ISSUE THREAD

**Issue by lgordey** [typograf/typograf#159]
В markdown 2 пробела в конце строки - переход на новую строку в том же абзаце.
Сейчас типограф это чистит.

Можно сделать что-то вроде режима "markdown" в котором типограф бы не ломал бы его стандартные правила. 
Ну или может я могу как-то просто переопределить это правило?

**Comment by hcodes** [comment]
Нужно отключить правило `common/space/delTrailingBlanks`.

**Comment by lgordey** [comment]
Понял, спасибо!
