### ISSUE TITLE
Конфигурация экранирования или парсера

### ISSUE THREAD

**Issue by ArmorDarks** [typograf/typograf#163]
Здравствуйте

Спасибо за замечательный инструмент.

К сожалению, не нашел возможности конфигурации экранирования или скормить типографу свой парсер.

Проблемы возникают с html-страницами, которые содержат темплейтинг. Порой, типограф неправильно их обрабатывает и ошибочно заменяет символы, которые являются частью темплейта, а не контента. К примеру, кавычки в `string`-литералах темплейта.

В нашем случае это [Nunjucks](https://mozilla.github.io/nunjucks/) с темплейтами вида `{{ 'текст' if something }}` или `{% set var = 'текст' %}`, однако разработчики могут использовать и другие популярные темплейт-языки, и для них может понадобиться специфическое экранирование определенных элементов.

Конечно, идеальней всего было бы иметь возможность настроить парсер, чтобы типограф не обрабатывал темплейты, однако работал со `string`-литералами в них. Но, ввиду потенциальной нетривиальности такой задачи, возможность настроить экранирование во время инициализации типографа тоже не помешает.

**Comment by hcodes** [comment]
Поможет метод `addSafeTag` — https://github.com/typograf/typograf/blob/dev/src/main.js#L271

**Comment by ArmorDarks** [comment]
Не увидел, спасибо. Уже лучше, чем ничего :)

Но, как я понимаю, это полностью исключит контенту между тегами?

Если была бы возможность подать regex, то, возможно, удалось бы написать правило так, чтобы исключился весь темплейтинг, кроме `string` в темплейтах

**Comment by hcodes** [comment]
[Дописал](https://github.com/typograf/typograf#%D0%9E%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B8%D0%BF%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B2-%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%BA%D0%B0%D1%85-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0) в README про отключение типографирования в текстах.

Подать регулярное выражение в метод `addSafeTag` [можно](https://github.com/typograf/typograf/blob/dev/src/main.js#L499),  но получится сложная регулярка, т.к. у `Nunjucks` богатый синтаксис.
