### ISSUE TITLE
Не удаляются неразрывные пробелы

### ISSUE THREAD

**Issue by hudochenkov** [typograf/typograf#165]
Почему-то не удаляется неразрывный пробел, из-за этого не ставится неразрывный пробел в нужно месте. В первом предложении неразрывный пробел стоит после тире, во втором предложении я его убрал:

![image](https://cloud.githubusercontent.com/assets/654597/18379521/b677f20a-767b-11e6-9ab3-4756de9536a4.png)

https://typograf.github.io/#!text=%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%2C%20%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82%2C%20%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA%20%D0%B8%20%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0%20%E2%80%94%C2%A0%D0%BD%D0%B0%20%D1%87%D1%82%D0%BE%20%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D0%B8%D1%82%D1%8C%20%D0%B2%D0%BD%D0%B8%D0%BC%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%B8%20%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B5%20%D0%B1%D0%BB%D0%BE%D0%B3%D0%B0%20%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D0%B8.

P. S. Спасибо за типограф! Работает очень круто!

**Comment by hcodes** [comment]
Не учтён неразрывный пробел после тире.
https://github.com/typograf/typograf/blob/dev/src/rules/ru/dash/main.js#L6

**Comment by hcodes** [comment]
v5.4.2
Теперь устанавливается неразрывный перед тире, если есть неразрывный пробел после тире.

**Comment by hudochenkov** [comment]
Спасибо!

Мне кажется, что правильнее будет не оставлять неразрывный пробел после тире, а заменять его на обычный пробел.

``` diff
- ['Правда -\u00A0небольшая ложь', 'Правда\u00A0—\u00A0небольшая ложь'],
+ ['Правда -\u00A0небольшая ложь', 'Правда\u00A0— небольшая ложь'],
```

Как вы думаете?

**Comment by hcodes** [comment]
Думал об этом. А если нужны будут неразрывные пробелы до и после тире, а типограф заменит неразрывный пробел на обычный?

**Comment by hudochenkov** [comment]
Я погуглил и везде пишут, что неразрывный пробел нужен перед тире, а после тире всегда обычный.

**Comment by hcodes** [comment]
Например, пользователь специально добавил неразрывные пробелы в текст `Правда\u00A0-\u00A0ложь`, чтобы не было переносов на новые строчки. После типографирования получится `Правда\u00A0- ложь`, ложь перенесётся на новую строку.

Я исхожу из того, что если есть неразрывные пробелы в тексте до начала типографирования, то они должны учитываться.

**Comment by hudochenkov** [comment]
Наверное вы правы. Пожалуй можно просто кастомное правило для себя написать, если нужно исправлять эту ошибку. Или же добавить опцию в правило. По умолчанию сохранять неразрывный пробел после тире, но при желании можно это отключить.

**Comment by hcodes** [comment]
[Написал](https://github.com/typograf/typograf#%D0%9D%D0%B5%D1%80%D0%B0%D0%B7%D1%80%D1%8B%D0%B2%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB%D1%8B) подробнее о неразрывных пробелах.
Поправил правило `common/nbsp/replaceNbsp`, теперь его можно использовать, если есть неправильно расставленные неразрывные пробелы.

v5.4.3
