### ISSUE TITLE
Форматирование чисел

### ISSUE THREAD

**Issue by trikadin** [typograf/typograf#168]
Есть ли планы по поддержке правила для форматирования чисел? Отбивать тысячи узким пробелом (&amp;thinsp;), точку менять на запятую.

**Comment by hcodes** [comment]
Правило можно сделать, но его придётся отключить по умолчанию.
Например, номер телефона, индекс, номер паспорта и что-то ещё будет разбито на тонкие пробелы.

**Comment by trikadin** [comment]
> его придётся отключить по умолчанию.

Это понятно. Возможно, я смогу на выходных время выделить -- ПР зашлю.

**Comment by hcodes** [comment]
Обсуждение в issue закончилось, закрываю.

**Comment by trikadin** [comment]
PR я всё-таки пришлю где-нибудь. Сейчас как-то времени не было.
