### ISSUE TITLE
В HTML типографируется title, что приводит к странностям

### ISSUE THREAD

**Issue by mkpankov** [typograf/typograf#172]
``` html
  <title>Большие бинари в моем Rust? (Why is a Rust executable large?) | Ржавый ящик</title>
```

преобразуется в

``` html
  <title>Большие бинари в моем Rust?<span class="typograf-oa-sp-lbracket"> </span><span class="typograf-oa-lbracket">(</span>Why is a Rust executable large?) | Ржавый ящик</title>
```

Из-за этого браузер выводит все эти "span" в заголовке окна.

Думаю, title не должен типографироваться.

Тестовый файл в архиве [why-big-bin.html.zip](https://github.com/typograf/typograf/files/517730/why-big-bin.html.zip)

**Comment by hcodes** [comment]
Забавный баг.
Сейчас типограф обрабатывает текст как единое целое. В этом и проблема. Его нужно научить (сделать) обрабатывать текст блоками. `title` это частный случай.
Например, незакрытая кавычка в `title` повлияет на кавычки внутри `body`. Правила в типографе при выполнении не знают в каком контексте (теге) выполняются.

**Comment by mkpankov** [comment]
А code ведь не типографируется - как так получается?

**Comment by hcodes** [comment]
[Эти теги](https://github.com/typograf/typograf/blob/dev/src/main.js#L473) не типографируются.
`<title>` можно было бы добавить в этот список, но в нём можно использовать HTML-сущности, а теги нельзя.

**Comment by hcodes** [comment]
v5.5.3
