### ISSUE TITLE
Не отключает типографирование  внутри тегов '[', ']'

### ISSUE THREAD

**Issue by vgrish** [typograf/typograf#180]
Согласно документации добавляю исключение
```
tp.addSafeTag('[', ']');
```
текст все равно обрабатывается

**Comment by hcodes** [comment]
``` js
tp.addSafeTag(/\[.*?\]/g);
```

или

``` js
tp.addSafeTag('\\[', '\\]');
```

Там регулярка составляется и из-за этого нужно экранировать лишний раз.

**Comment by hcodes** [comment]
Добавлю данный случай в документацию.

**Comment by vgrish** [comment]
Спасибо! все отлично работает.
