### ISSUE TITLE
Неразрывные пробелы в инициалах и сокращениях

### ISSUE THREAD

**Issue by rusty-key** [typograf/typograf#181]
Привет! Спасибо за шикарный инструмент :)

Кажется, что неправильно расставляются неразрывные пробелы в инициалах и сочетаниях.

`А. С. Пушкин → А._С._Пушкин`, но `Пушкин А. С. → Пушкин_А. С.`. Во втором варианте перед второй инициал не приклеивается. Так и задумано? Почему?

Также судя при включённом правиле `ru/nbsp/abbr` не происходит склеивания сокращений вроде `т. е.` и `т. д.`

**Comment by hcodes** [comment]
С инициалами не всё так просто. Второй инициал может относится к другому слову. Есть спорные случаи.

С `т. е.` перепроверю.

**Comment by rusty-key** [comment]
> С инициалами не всё так просто. Второй инициал может относится к другому слову. Есть спорные случаи.

А можно на такие случаи посмотреть? Возможно, это краевые случаи, которые в нашем проекте можно игнорировать и я просто переопределю правило.

**Comment by hcodes** [comment]
`Москву И. И. Иванов представлял себе так.` Инициалы относятся к Москву или к Иванову?

**Comment by hcodes** [comment]
`Москву И. И. Иванов представлял себе так.` Инициалы относятся к Москву или к Иванову?

**Comment by hcodes** [comment]
Можно учесть случаи когда нет спорных моментов.
Например, фамилии с инициалами перечислены через запятую.
`Сидоров_И._И., Петров_А._А.`

**Comment by rusty-key** [comment]
> Можно учесть случаи когда нет спорных моментов.
> Например, фамилии с инициалами перечислены через запятую.
> Сидоров_И._И., Петров_А._А.

Ага, или если одно из слов не начинается с прописной буквы:

```
Московскую подземку И._И._Иванов представлял себе так.
Иванов_И._И. представлял себе Москву так.
```

А в спорных случая как раз можно и не ставить, пусть редактор сам разбирает.

**Comment by hcodes** [comment]
Поправил неразрывные пробелы в сокращениях #188.
v5.6.0
