### ISSUE TITLE
При включении висячей пунктуации пунктуация в тексте типографируется неправильно

### ISSUE THREAD

**Issue by mkpankov** [typograf/typograf#184]
Пример:

https://rustycrate.ru/%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8/2016/11/10/rust-1.13.html#drughiie-zamietnyie-izmienieniia

![screenshot from 2016-11-11 12 40 06](https://cloud.githubusercontent.com/assets/393741/20210728/0647da54-a80c-11e6-9b5d-16b3da5c8d02.png)

Проблема в
> хранил «флаг

Кавычка приклеилась к предыдущему слову.

Технически всё верно - кавычка в классе

```
<span class="typograf-oa-n-lquote">«</span>
```

на классе CSS

```
.typograf-oa-n-lquote {
    margin-left: -0.44em;
}
```

Но я не понимаю, как это тогда должно работать.

Как отличаются кавычки, которые должны висеть, от тех, которые в середине текста и не должны висеть? Похоже что типограф назначает всем одинаковый класс.

Типограф вызывается так

```
typograf -l ru -e 'ru/optalign/*' <file>
```

Исходный HTML здесь - [rust-1.13.html.zip](https://github.com/typograf/typograf/files/585467/rust-1.13.html.zip)

**Comment by hcodes** [comment]
Гляну на выходных.

**Comment by hcodes** [comment]
хранил «флаг

```
хранил<span class="typograf-oa-sp-lquote"> </span><span class="typograf-oa-lquote">«</span>флаг
```

хранил
«флаг

```
хранил
<span class="typograf-oa-lquote">«</span>флаг
```

Из-за переноса не ставится пробел с классом `typograf-oa-sp-lquote`.

**Comment by hcodes** [comment]
v5.6.0
