### ISSUE TITLE
Кавычки в ссылке неправильно типографируются в висячем режиме

### ISSUE THREAD

**Issue by mkpankov** [typograf/typograf#192]
Судя по всему, происходит в случае перевода строки перед ссылкой.

Исходный HTML:

```
                <p>Перевод статьи <a href="https://pascalhertleif.de">Pascal Hertleif</a>
<a href="https://pascalhertleif.de/artikel/good-practices-for-writing-rust-libraries">“Good Practices for Writing Rust Libraries”</a>
(2015.10.24).</p>
```

Результат:

![screenshot from 2016-11-26 17-06-40](https://cloud.githubusercontent.com/assets/393741/20640822/c792f91a-b3fa-11e6-95b3-f81f58d2f153.png)

Запуск типографа:
```
typograf -e 'ru/optalign/*' -l ru <file>
```

Полный исходный [HTML](https://github.com/typograf/typograf/files/614258/html.zip)

**Comment by hcodes** [comment]
Типограф прячет теги с помощью UTF-8 символов из приватной зоны. Пока нет возможности понять, что спрятанный тег блочный или строковой.

**Comment by hcodes** [comment]
Кстати, кавычки лучше вынести из ссылки.

**Comment by mkpankov** [comment]
> Кстати, кавычки лучше вынести из ссылки.

@hcodes в смысле в качестве workaround, или по какой-то ещё причине?

**Comment by hcodes** [comment]
http://www.artlebedev.ru/kovodstvo/sections/143/#12

**Comment by hcodes** [comment]
v6.0.1

P. S.: Появилось правило `common\punctuation\quoteLink`, которое выносит кавычки из ссылок.
