### ISSUE TITLE
"Висячий" предлог "без"

### ISSUE THREAD

**Issue by sombro** [typograf/typograf#194]
```
Безналичный расчёт с НДС -> Безналичный расчёт с&nbsp;НДС
Безналичный расчёт без НДС -> Безналичный расчёт без НДС
```

Привет!

Почему-то "с" как висячий предлог Типограф правильно определил, а "без" — нет.
Если что-то делаю не так, подскажите пожалуйста, что включить, чтобы между "без" и "НДС" тоже появился &nbsp; , если нет, то это баг :) 

Спасибо.

P.S. Плагин использую с настройками по-умолчанию.

**Comment by hcodes** [comment]
https://github.com/typograf/typograf/blob/dev/src/rules/common/nbsp/afterShortWord.js
Нужно поменять настройку у правила:
```js
var  tp = new Typograf({lang: 'ru'});
tp.setting('common/nbsp/afterShortWord', 'lengthShortWord', 3);
```

**Comment by sombro** [comment]
А... То есть предлог или не предлог плагин не понимает, понимает только длину слова.
Спасибо за подсказку!
