### ISSUE TITLE
Доработки по кавычкам

### ISSUE THREAD

**Issue by hcodes** [typograf/typograf#222]
- ~~поменять вид кавычек у `en-GB`;~~
- ~~для французских кавычек добавить отбивку тонким неразрывным пробелом;~~
- ~~поправить расстановку кавычек для случая, где левая и правая кавычки одинаковые (`sv` и `fi`).~~

**Comment by Limych** [comment]
Некорректно отрабатывает кавычки-ёлочки в начале текста.
Пример: `<p>«Куда ты ведёшь нас?.. не видно ни зги! —</p>` превращается в `<p>»Куда ты ведёшь нас?.. не видно ни зги! —</p>`

**Comment by hcodes** [comment]
Это из-за тега и незакрытой кавычки. Поправлю и добавлю тест.

**Comment by Limych** [comment]
Прошу извинить, кавычек я только в примере не закрыл. Когда обнаружил баг, кавычка вторая была.
Причина в теге. Сейчас лечится проставлением пробела между ним и кавычкой.

**Comment by hcodes** [comment]
А можно полный пример посмотреть?

**Comment by Limych** [comment]
Да, конечно. Сейчас он выглядит так:
```html
                <p> «Куда ты ведёшь нас?.. не&nbsp;видно ни&nbsp;зги!&nbsp;—<br />
                Сусанину с сердцем вскричали враги,&nbsp;—<br />
                Мы вязнем и&nbsp;тонем в&nbsp;сугробинах снега;<br />
                Нам, знать, не&nbsp;добраться с&nbsp;тобой до&nbsp;ночлега.<br />
                Ты сбился, брат, верно, нарочно с&nbsp;пути;<br />
                Но&nbsp;тем Михаила тебе не&nbsp;спасти!..»</p>
                <p class="text-right"><nobr>К. Ф. Рылеев,</nobr> «Иван Сусанин»</p>
```
Пробел в начале абзаца добавлен для исправления этого бага.

Также баг возникал, когда первая строчка была оформлена в виде отдельного заголовка (с закрыванием кавычек).

**Comment by hcodes** [comment]
Странно, проверил полный пример на сайте https://typograf.github.io/ и ошибки нет.

Если ввести:
```html
<p>«Куда ты ведёшь нас?.. не&nbsp;видно ни&nbsp;зги!&nbsp;—<br />
```
То ошибка будет:
```html
<p>»Куда ты ведёшь нас?.. не видно ни зги! —<br />
```

**Comment by Alexufo** [comment]
А такой пример?

    “ uoiyu iuy iuy “kjyiuiu” iu” 

на выходе 

    " uoiyu iuy «kjyiuiu» iu«

**Comment by hcodes** [comment]
Спасибо, добавлю в тесты.

**Comment by motorin** [comment]
Да-да, ошибка все еще есть. Кажется, что если кавычка стоит первым символом в блоке (раз теперь по блокам расстановка работает), то она всегда должна быть открывающей.

Мой пример, когда цитата занимает два абзаца, например, 

```
<p>"Я всегда с гордостью носил военную форму...</p>

<p>...Я переживал очень тяжёлую депрессию. "</p>
```

На выходе:
```
»Я всегда с гордостью носил...
```

Это раз.
И второе — если внутрь такой длинной цитаты вставлять еще кавычки для второй вложенности или для третьей, то они, конечно, "сломанные".  

Возможно, проверка должна быть сложной, на уровне, если закрывающих кавычек в блоке не хватает, то берем в расчет следующий блок, и так далее, пока не хватит окончательных закрывающих кавычек в очередном блоке.  (но тут я не уверен, конечно, нужны тесты и проверки).

Глобально расстановка по блокам — удобная штука, но вот с такими цитатами проблема.

**Comment by hcodes** [comment]
Первое починил, для второго набираю тесты. Ещё есть интересный момент, когда кавычки отбиты с обоих сторон пробелами или вообще без пробелов.

**Comment by Alexufo** [comment]
А разве отбитие пробелов как то должно влиять на подсчет пар кавычек? Если в блоке четное 
количество - пары открывающих и закрывающих ясны. А следовательно, не имеют значения пробелы да и никак не должны иметь. Они все равно всегда будут ошибочно неопределенно расставленны осознанно или нет.

**Comment by hcodes** [comment]
С расстановкой кавычек стало лучше, v6.6.0.
С кавычками отбитыми пробелами буду разбираться в отдельной задаче.
