### ISSUE TITLE
Применение ru/punctuation/hellip для английского текста

### ISSUE THREAD

**Issue by ai** [typograf/typograf#245]
Хочу заменять три точки `...` на многоточие `…` в английском тексте. Пишу:

```js
const en = new Typograf({ locale: 'en-US' })
en.disableRule('*')
en.enableRule('common/nbsp/*')
en.enableRule('common/punctuation/apostrophe')
en.enableRule('ru/punctuation/hellip')

console.log(en.execute('next...'))
```

Но он возвращает `next...` с тремя точками.

@hcodes наверное, проблема в то, что я использую русское правило для английского.

Как починить?

Или может стоит это правило перенести в `common/`?

**Comment by hcodes** [comment]
В `common` не получится перенести правило с многоточием, слишком много различий в разных языках.
https://en.wikipedia.org/wiki/Ellipsis#In_different_languages

**Comment by hcodes** [comment]
Или добавить [своё правило](https://github.com/typograf/typograf#%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B5-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE).

**Comment by ai** [comment]
Просто правило уже есть, если я добавлю свою (я так пока и сделал), о я потеряю обновления.

Может добавить возможность включать правила, даже язык не совпадает?

**Comment by hcodes** [comment]
Нет, лучше правило:
```js
Typograf.addRule({
    name: 'en-US/punctuation/hellip',
    handler: function(text) {
        return text.replace(/(^|[^.])\.{3}([^.]|$)/g, '$1…$2');
    }
});
```

**Comment by ai** [comment]
Может добавить его в стандартную поставку?

**Comment by hcodes** [comment]
Хорошо, почитаю подробнее про многоточие и добавлю.

**Comment by hcodes** [comment]
[v6.4.0](https://github.com/typograf/typograf/releases/tag/v6.4.0)

**Comment by ai** [comment]
@hcodes наличие `return context.prefs.locale[0] === 'ru' ?` в `hellip` делает его бессмыленным в `common` :(. Я всё равно не могу применить его к английскому тексту.

**Comment by hcodes** [comment]
@ai Какой `locale` выставлен в `new Typograf(...)`? И какой текст обрабатывается (русские и английские буквы)?

**Comment by hcodes** [comment]
Выбрал американскую локаль:
https://typograf.github.io/#!text=Hello...

`&hellip;` появляется.

**Comment by ai** [comment]
Упс, я в своём коде перепутал переменную
