### ISSUE TITLE
Применить ко всему документу или DOM объекту

### ISSUE THREAD

**Issue by ink-ru** [typograf/typograf#246]
В документации не указано как применить библиотеку Применить ко всему документу или DOM объекту по селектору.

**Comment by hcodes** [comment]
Спасибо, обязательно напишу.

**Comment by hcodes** [comment]
https://github.com/typograf/typograf#%D0%92-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5

**Comment by ink-ru** [comment]
Спасибо огромное!
