### ISSUE TITLE
Типографировать текст отдельными кусками

### ISSUE THREAD

**Issue by hcodes** [typograf/typograf#248]
Вырезать текст с тегами и типографировать отдельно от всего текста.
Теги:
- h1-h6
- title
- p
- select, option
- summary
- legend

**Comment by motorin** [comment]
+1

Мы, например, работаем с большими текстами, где внутри часто тройные вложенности кавычек. И когда одна какая-нибудь не так стоит — кавычки летят во всем тексте. И очень-очень сложно искать, где же проблема. Если бы типограф работал по отдельным параграфам (любым блокам) — это сильно бы облегчило.

Еще может облегчить подсветка (span class="error" какой-нибудь) непарных кавычек. Но это, очевидно, заметно сложнее.

**Comment by hcodes** [comment]
Обработка  частями готова, v6.5.0.
Проверку кавычек нужно прикрутить на https://typograf.github.io
