### ISSUE TITLE
Ситуация с пробелами в tinymce

### ISSUE THREAD

**Issue by Alexufo** [typograf/typograf#259]
Я в легком замешательстве:

Код пропускает текст через типограф при вставке из буфера. Он рабочий так как кавычки  на елочки меняются, но игнорируются полностью дубликаты пробелов.

То есть фраза:   `ttt              "dd"` превращается в  `ttt             «dd».` но куча пробелов между не фильтруются.
```
tinymce.PluginManager.add('za_typograf', function(editor) {
	 editor.on('PastePreProcess', function (e) {
		var tp = new Typograf({locale: ['ru', 'en-US']});
		e.content = tp.execute(e.content);
    });
});
```

Если вписать строку  `e.content = tp.execute('ttt              "dd"');`  все отлично, но вставка переменной приводит к описанной проблеме игнорирования фильтрации пробелов. Тип e.content строка.
Даже в теории не пойму в чем может быть проблема.

**Comment by hcodes** [comment]
Tinymce добавляет вместо обычных пробелов неразрывные.
![mozilla firefox 2017-10-06 00 04 23](https://user-images.githubusercontent.com/157520/31252528-24c856cc-aa2a-11e7-8bf8-ecde08c6abec.png)

Нужно включить правило `common/nbsp/replaceNbsp` и типограф будет заменять неразрывные пробелы на обычные перед типографированием.
```
var tp = new Typograf({locale: ['ru', 'en-US']});
tp.enableRule('common/nbsp/replaceNbsp');
```

**Comment by Alexufo** [comment]
гений
