### ISSUE TITLE
Объединение тегов

### ISSUE THREAD

**Issue by Alexufo** [typograf/typograf#270]
После копипасты в коде обнаруживается это

    <em>O</em> <em>tempora!</em> <em>O</em> <em>mores!</em>

Но ведь логично предположить, что если за закрывающим тегом идет такой же открывающий, можно объединить их в это

     <em>O tempora! O mores!</em>?

Не нашел такого функционала, думаю полезная вещь.

**Comment by hcodes** [comment]
Больше подходит для оптимизации HTML.
