### ISSUE TITLE
правила вложенных кавычек

### ISSUE THREAD

**Issue by Alexufo** [typograf/typograf#276]
это правило из примера

    tp.setSetting('common/punctuation/quote', 'ru', {left: '"', right: '"', removeDuplicateQuotes: true});

Делает все кавычки " " . А не только вложенные. Вот образец

    затасканные приколы, типа: «Девушки, звоните мне на «Каламбия пикчерс». Сек-суальный шок 
    гарантирую. Джек Николсон»

**Comment by hcodes** [comment]
Данная настройка делает все кавычки как `"` и удаляет сдвоенные.
```js
tp.setSetting('common/punctuation/quote', 'ru', {left: '"', right: '"', removeDuplicateQuotes: true});
```

Если нужно, чтобы вложенные кавычки были вида `"`, тогда настройки будут такие:
```js
tp.setSetting('common/punctuation/quote', 'ru', {left: '«"', right: '»"'});
```

Настройки по умолчанию для русских кавычек:
```js
tp.setSetting('common/punctuation/quote', 'ru', {left: '«„‚', right: '»“‘'});
```
