### ISSUE TITLE
Частично некорректная перестановка символа валюты в RU локали

### ISSUE THREAD

**Issue by dudeonthehorse** [typograf/typograf#277]
Source
```
<h3>Как отмывали $9 млрд</h3>
<p>Отмыли от $4 до $9 млрд</p>
<h3>Как отмывали <span>$9 млрд</span></h3>
<p>Отмыли от <span>$4</span> до <span>$9 млрд</span></p>
```

Result `ru`
```
<!-- wrong -->   <h3>Как отмывали 9 млрд $</h3>
<!-- wrong -->   <p>Отмыли от 4 $ до 9 млрд $</p>
<!-- correct --> <h3>Как отмывали <span>$9 млрд</span></h3>
<!-- correct --> <p>Отмыли от <span>$4</span> до <span>$9 млрд</span></p>
```

Result `en-US`
```
<!-- correct --> <h3>Как отмывали $9 млрд</h3>
<!-- correct --> <p>Отмыли от $4 до $9 млрд</p>
<!-- correct --> <h3>Как отмывали <span>$9 млрд</span></h3>
<!-- correct --> <p>Отмыли от <span>$4</span> до <span>$9 млрд</span></p>
```

Аналогичная проблема с Евро и Йенами. С рублем все окей, так как он указывается не в начале строки, а в конце.

Я убрал из `result` неразрывные пробелы для читабельности кода.

**Comment by hcodes** [comment]
Спасибо, посмотрю.

**Comment by hcodes** [comment]
А. Мильчин рекомендует знак доллара ставить после чисел. Если это поведение не устраивает, то можно отключить правило `ru/money/currency`.

Да, есть ошибка в периодах, сейчас Типограф расставляет знак доллара неправильно. ```<p>Отмыли от 4 $ до 9 млрд $</p>```

**Comment by hcodes** [comment]
Правило `ru/money/currency` отключил.
v6.7.0
