### ISSUE TITLE
[новая функция] м-тир на английском

### ISSUE THREAD

**Issue by revelt** [typograf/typograf#286]
Во-первых, спасибо за эту библиотеку. 👍 

Было бы неплохо добавить преобразования дефис в _m-dash_ (на английском):

`The thing we noticed - m-dashes were missing!`

конвертировать в:

`The thing we noticed — m-dashes were missing!`

Ф.И.Й.: https://www.npmjs.com/package/typographic-em-dashes

Спасибо.

П.С. Тоже есть https://www.npmjs.com/package/typographic-en-dashes

**Comment by hcodes** [comment]
👍

**Comment by hcodes** [comment]
Closes #316
