### ISSUE TITLE
Странное поведение с запятыми

### ISSUE THREAD

**Issue by ai** [typograf/typograf#295]
Если оттипографировать этот текст:

```
Михаэль Шарналь попросил читателей в Твиттере поделиться полезными CSS-снипетами https://twitter.com/justmarkup/status/974573989497593856, а потом собрал их с пояснениями у себя в блоге — https://justmarkup.com/log/2018/03/collection-of-css-snippets/
```

Вот тактим типографом:

```js
const russianRules = new Typograf({ locale: 'ru' })
russianRules.disableRule('common/symbols/cf')
russianRules.disableRule('common/space/*')
russianRules.disableRule('common/nbsp/*')
russianRules.disableRule('ru/money/*')
russianRules.disableRule('ru/date/*')
russianRules.disableRule('ru/nbsp/*')
```

то типограф вставитт ещё одну запятую после ссылки и перед «а» — `,, а потом собрал`

@hcodes как всегда спасибо за очень полезный проект

**Comment by hcodes** [comment]
Это из-за того, что запятая стоит рядом со ссылкой. Перед типографированием ссылка прячется и лишняя запятая добавляется к «a». Правило «ru/punctuation/ano» необходимо запускать перед обработкой ссылок, поправлю.

**Comment by hcodes** [comment]
v6.7.1
