### ISSUE TITLE
Расширение для vscode

### ISSUE THREAD

**Issue by perseus-me** [typograf/typograf#303]
Привет!

Собрал расширение для Visual Studio Code, за основу взял расширение для atom.

https://marketplace.visualstudio.com/items?itemName=rusnasonov.vscode-typograf
https://github.com/rusnasonov/vscode-typograf

Можно взять логотип для расширения?

**Comment by hcodes** [comment]
Можно, спасибо за расширение.

**Comment by perseus-me** [comment]
Пожалуйста ;)

**Comment by hcodes** [comment]
Добавил ссылку на это расширение в README.
