### ISSUE TITLE
Не могу отключить Апостроф

### ISSUE THREAD

**Issue by Mezzzanine** [typograf/typograf#305]
Типограф заменяет ' на &apos. не могу найти место где это происходит и отключить..
Также не работает экранирование тэгом в html/nunjacks

**Comment by hcodes** [comment]
```js
tp.disableRule('common/punctuation/apostrophe');
```

**Comment by hcodes** [comment]
> Также не работает экранирование тэгом в html/nunjacks

Как это относится к Типографу?
