### ISSUE TITLE
Неразрывный пробел в числах и пробелы вокруг тегов

### ISSUE THREAD

**Issue by dkrnl** [typograf/typograf#307]
Здравствуйте 
1.  [Так есть nbsp](https://typograf.github.io/#!text=%3Cspan%3E%20123%20456%2C789%20%3C%2Fspan%3E) -- вокруг тегов есть пробел
2.  [Так нет nbsp](https://typograf.github.io/#!text=%3Cspan%3E123%20456%2C789%3C%2Fspan%3E) --- вокруг тегов нет пробелов

Не уверен что это баг, может подскажите настройки? 

Спасибо!

**Comment by hcodes** [comment]
Это ошибка, данный случай не учтён.

**Comment by hcodes** [comment]
v6.7.3
