### ISSUE TITLE
Слова, начинающиеся с точки, и common/space/delBeforePunctuation

### ISSUE THREAD

**Issue by alyrik** [typograf/typograf#312]
Фразу «Нам нужен .Net-разработчик.» типограф преобразует в «Нам нужен.Net-разработчик.».

Можно ли как-то избежать подобных случаев, не отключая правило?

**Comment by hcodes** [comment]
Можно. Нужно доработать правило, чтобы появилась возможность добавлять исключения.

**Comment by hcodes** [comment]
#384
