### ISSUE TITLE
Не ставится пробел после точки.

### ISSUE THREAD

**Issue by kuzmichus** [typograf/typograf#313]
В фразе вида:

> Слово.Второе.

Ожидалось что после первой точки перед началом второго предложения будет пробел, но он не проставляется.
Хотя, если вместо точки будет запятая, то пробел проставиться. по моему это ошибка.

**Comment by hcodes** [comment]
Да, это ожидаемое поведение.
Например: Яндекс.Деньги. Тут пробел не нужен.

**Comment by hcodes** [comment]
В названиях файлов также есть точки.

**Comment by kuzmichus** [comment]
Да, не однозначно.
Спасибо, добавил для себя индивидуальное правило.

**Comment by hcodes** [comment]
👍
