### ISSUE TITLE
French Narrow non breaking space support

### ISSUE THREAD

**Issue by borisrorsvort** [typograf/typograf#317]
Narrow non breaking space is required for big punctuation in French, sometimes inaccurately referred to as ”double punctuation“ (before ;, ?, !, », › and after «, ‹; today often also before :)

https://en.wikipedia.org/wiki/Non-breaking_space

Though markdown mostly dont support non breaking space in general so the only working solution is to actually add the ascii version.

You can still add the unicode but that would just disapear at render.

**Comment by hcodes** [comment]
There is support for French quotes
https://github.com/typograf/typograf/blob/dev/src/data/fr/quote.js
https://github.com/typograf/typograf/blob/dev/src/rules/common/punctuation/quote.fr.spec.js

For other punctuation, I try to write a rule.

**Comment by Alph2** [comment]
What about:
```
Typograf.addRule({
  name: 'common/space/french',
  handler: function handler(text) {
    return text.replace(/(\s?)([?!:;])(\s|\Z)/g, '$1\u202F$2$3');
  }
});
```
Seems to be working ok.

**Comment by Alph2** [comment]
Better (also replace existing non-break space with narrow non break)

```
Typograf.addRule({
  name: 'common/space/french',
  handler: function handler(text) {
    return text.replace(/(\s?|\u00A0?)([?!:;])(\s|\Z)/g, '$1\u202F$2$3');
  }
});
```

**Comment by Alph2** [comment]
Better (also replace existing non-breaking space with narrow non breaking space)
```
Typograf.addRule({
  name: 'common/space/french',
  handler: function handler(text) {
    return text.replace(/(\s?|\u00A0?)([?!:;])(\s|\Z)/g, '\u202F$2$3');
  }
});
```
