### ISSUE TITLE
common/symbols/cf: аббревиатура B2B и B2C 

### ISSUE THREAD

**Issue by dkrnl** [typograf/typograf#319]
Доброго времени суток!

обнаружил немного неверное поведение правила `common/symbols/cf` -- [ссылка на тест](https://typograf.github.io/#!text=%D0%90%D0%B1%D0%B1%D1%80%D0%B5%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D1%8B%3A%20B2B%20%D0%B8%20B2C%20)

**Comment by hcodes** [comment]
Нужно учитывать символы перед числом.

**Comment by hcodes** [comment]
https://github.com/typograf/typograf/pull/322
