### ISSUE TITLE
Неверно проставляется неразрывный пробел в правиле ru/dash/main

### ISSUE THREAD

**Issue by nikolayemrikh** [typograf/typograf#321]
https://github.com/typograf/typograf/blob/dev/src/rules/ru/dash/main.js

Искал долго в чём подвох, не мог понять, почему не отключается замена неразрывных пробелов таким образом:

```js
tp.disableRule(`ru/nbsp/*`);
tp.disableRule(`common/nbsp/*`);
tp.enableRule(`common/nbsp/replaceNbsp`);
```

Начал постепенно всё включать и увидел, что коде обработки `ru/dash/main` у вас проставляется неразрывный пробел в перед тире:
return text.replace(re, '**\u00A0**\u2014$3');

**Comment by nikolayemrikh** [comment]
Хотя более похоже на то, что это правило должно быть не в категории dash, а в категории nbsp

**Comment by hcodes** [comment]
По умолчанию типограф не заменяет неразрывные пробелы на обычные перед типографированием, чтобы не удалить ранее проставленные неразрывные пробелы. Если в тексте неправильно расставлены неразрывные пробелы, включите правило `common/nbsp/replaceNbsp`.

Если неразрывные пробелы необходимо заменить на обычные после типографирования:
`text.replace(/\u00a0/g, '')`

**Comment by hcodes** [comment]
Неразрывный пробел перед тире необходим, иначе тире перенесётся на новую строку и будет прямая речь, а это ошибка.

Правило `ru/dash/main` можно разбить на два: замена дефиса на тире и неразрывный пробел перед тире. Но особого смысла пока в этом не вижу.
