### ISSUE TITLE
Неразрывный пробел у даты в формате дд.мм.гггг при включенном правиле ru/nbsp/abbr

### ISSUE THREAD

**Issue by GalGrigoryeva** [typograf/typograf#325]
https://github.com/typograf/typograf/blob/dev/src/rules/ru/nbsp/abbr.js

При тестировании обнаружила, что данное правило добавляет неразрывный пробел между точкой и сокращением месяца: `дд.мм.гггг → дд._мм.гггг`.

При отключении правила пробел пропадает.

Это ожидаемое поведение или всё-таки ошибка?

**Comment by hcodes** [comment]
Это баг.

**Comment by hcodes** [comment]
v6.8.2
