### ISSUE TITLE
удаляется форматирование

### ISSUE THREAD

**Issue by lib-lab** [typograf/typograf#330]
Привет! 
Спасибо, за Типограф и за Восстановление буквы «ё» в русских текстах.

Скорее всего, я сейчас пишу о своей невнимательности, а не об ошибке. Каждый раз, когда я пытаюсь оттипографировать текст, типограф удаляет всё форматирование (самое главное, переносы каретки). 
Я, вроде, попытался убрать те галочки, которые, как мне казалось, могут на это влиять, но результата не получил. 

Подскажите, пожалуйста, если дело в настройках, как сделать так, чтобы форматирование сохранялось?

**Comment by hcodes** [comment]
![Типограф - Mozilla Firefox 2019-07-17 23 37 54](https://user-images.githubusercontent.com/157520/61409985-12a40c80-a8ec-11e9-907c-7beae800b5ba.png)

**Comment by lib-lab** [comment]
Нет, это я пробовал (попробовал ещё раз). 
Удаляет даже один перенос строки.

**Comment by hcodes** [comment]
Нужно сбросить настройки на https://typograf.github.io/#!prefs
Кликнуть на кнопку «По умолчанию».
На каком тексте возникает проблема?

**Comment by lib-lab** [comment]
Настройки сбросил, поведение сохранилось.
Тестирую в веб-интерфейсе джимейла, FF, win10



сб, 20 июл. 2019 г. в 09:01, Denis Seleznev <notifications@github.com>:

**Comment by hcodes** [comment]
![Add-ons Manager - Mozilla Firefox 2019-07-24 20 46 21](https://user-images.githubusercontent.com/157520/61816026-2a334600-ae54-11e9-9a41-5c1204339348.png)
Это в дополнении к браузеру?

**Comment by lib-lab** [comment]
да.  Firefox

ср, 24 июл. 2019 г. в 19:58, Denis Seleznev <notifications@github.com>:

**Comment by hcodes** [comment]
https://github.com/red-typography/red-typography-webextension

**Comment by lib-lab** [comment]
в смысле, я не туда написал?

**Comment by hcodes** [comment]
Да, хорошо бы перенести.

**Comment by lib-lab** [comment]
ок, без проблем
спасибо!
