### ISSUE TITLE
Перемещение курсора в конец поля ввода.

### ISSUE THREAD

**Issue by kemerovo-man** [typograf/typograf#332]
Здравствуйте, спасибо за Ваш типограф, используем его на нашем новостном сайте. Он привязан к текстовым полям ввода и работает на лету, при вводе заменяет кавычки и т.д. Одна беда, журналисты жалуются что после замены курсор перемещается в конец поля ввода. Можно ли с этим что-то сделать?

**Comment by hcodes** [comment]
Можно логику с каретками взять из [autotypograf](https://github.com/typograf/jquery-typograf/blob/gh-pages/autotypograf.vanilla.js).

**Comment by hcodes** [comment]
https://github.com/typograf/jquery-typograf

**Comment by kemerovo-man** [comment]
Спасибо большое.
