### ISSUE TITLE
Работа правила `common/nbsp/beforeShortLastNumber`

### ISSUE THREAD

**Issue by peremenov** [typograf/typograf#363]
Вероятно правило должно применяться также для предложения, заканчивающегося `)`, но этого не происходит.

Например в заголовке число относится к стоящему перед ним слову: `Рассказ о поездке (часть 1)`. Сейчас переносится последняя часть предложения, содержащая только цифру: `1)`.

Спасибо

**Comment by hcodes** [comment]
Спасибо за ошибку. Исправлено в https://github.com/typograf/typograf/pull/364.
