### ISSUE TITLE
Неправильно работает правило `common/punctuation/quote`

### ISSUE THREAD

**Issue by yacodes** [typograf/typograf#372]
При обработке следующего текста с дефолтными настройками:
> «Копрорация "Амбрелла"»&nbsp;У многих российских проектов окно между кинотеатральным и цифровым релизом и раньше было меньше, чем у зарубежной продукции. Но сейчас и они сокращаются. Хоррор «Яга. Кошмар темного леса» появился онлайн менее чем через месяц после старта в кинотеатрах, такая же история — с ««Отелем "Белград"»

Результат становится таким:
> «Копрорация «Амбрелла»» У&nbsp;многих российских проектов окно между кинотеатральным и&nbsp;цифровым релизом и&nbsp;раньше было меньше, чем у&nbsp;зарубежной продукции. Но&nbsp;сейчас и&nbsp;они сокращаются. Хоррор «Яга. Кошмар темного леса» появился онлайн менее чем через месяц после старта в&nbsp;кинотеатрах, такая&nbsp;же история&nbsp;— с&nbsp;««Отелем «Белград»»

Ожидаемый результат:
> «Копрорация „Амбрелла“» У&nbsp;многих российских проектов окно между кинотеатральным и&nbsp;цифровым релизом и&nbsp;раньше было меньше, чем у&nbsp;зарубежной продукции. Но&nbsp;сейчас и&nbsp;они сокращаются. Хоррор «Яга. Кошмар темного леса» появился онлайн менее чем через месяц после старта в&nbsp;кинотеатрах, такая&nbsp;же история&nbsp;— с&nbsp;«Отелем „Белград“»

**Comment by hcodes** [comment]
Лишняя открывающая кавычка `««Отелем «Белград»»`.

**Comment by yacodes** [comment]
Да. Но остальные кавычки в тексте перестают форматироваться из-за лишней открывающей кавычки в конце.

**Comment by hcodes** [comment]
Спасибо за баг, поменял логику расстановки кавычек.
Сейчас, если будет найдено не соответствие количеству левых и правых кавычек, Типограф будет применять только кавычки первого уровня (лапки).
Как будет, Типограф расставит кавычки разного уровня (лапки и ёлочки). Это поможет лучше найти изначально неправильно расставленные кавычки в тексте.

> «Корпорация „Амбрелла“» У многих российских проектов окно между кинотеатральным и цифровым релизом и раньше было меньше, чем у зарубежной продукции. Но сейчас и они сокращаются. Хоррор «Яга. Кошмар темного леса» появился онлайн менее чем через месяц после старта в кинотеатрах, такая же история — с «„Отелем „Белград“»

**Comment by hcodes** [comment]
https://github.com/typograf/typograf/pull/394
