### ISSUE TITLE
«Как-то» vs «Как то»

### ISSUE THREAD

**Issue by dotterian** [typograf/typograf#381]
[Хроники войны за «как то»](http://gramma.ru/RUS/?id=13.53)

TLDR; Есть в русском языке достаточно иключительный случай: использование «как то» перед перечислением.
_«В смешанных лесах встречаются разнообразные деревья, как то: береза, осина, кедр, сосна»_

В официальных правилах русского языка такой случай не закреплён и для простоты лепят дефис везде, но мне сегодня принесли жалобу на то, что типограф превратил «как то» перед перечислением в «как-то», я углубился в тему и склонен считать, что типограф не прав.

Предлагаемое решение: внести «как то» в исключения в правиле `rus/dash/to` и вынести автозамену конкретно этого случая в отдельное правило `rus/dash/kakto` дабы обеспечить большую гибкость в данном вопросе и поддержать обе стороны.

**Comment by hcodes** [comment]
Да, хорошая идея добавить отдельное правило.

**Comment by hcodes** [comment]
Появится новое правило `ru/dash/kakto`.

**Comment by hcodes** [comment]
https://github.com/typograf/typograf/pull/405
