### ISSUE TITLE
Удаление пробела перед пунктуацией и калибры

### ISSUE THREAD

**Issue by dotterian** [typograf/typograf#382]
> Калибр стрелкового оружия измеряется в долях дюйма. В записи ноль целой части числа и обозначение единицы измерения опускаются, в качестве десятичного разделителя используется точка: .45, .450.
— [Wikipedia](https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BB%D0%B8%D0%B1%D1%80#%D0%9A%D0%B0%D0%BB%D0%B8%D0%B1%D1%80_%D0%BD%D0%B0%D1%80%D0%B5%D0%B7%D0%BD%D0%BE%D0%B3%D0%BE_%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%BA%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D0%BE%D1%80%D1%83%D0%B6%D0%B8%D1%8F)

В правиле `common/space/delBeforePunctuation` отсутствует negative lookahead для цифр, в связи с чем после типографирования «калир .45» имеем «калибр.45».

Стоит либо добавить подобную проверку, либо подумать над api настроек для правил.
_(Допускаю, что совершаю ошибку, принудительно прогоняя через типограф все тексты на сайте, но моё стремление наносить миру добро уже не остановить)_

Предлагаемые изменения:

```diff
export default {
    name: 'common/space/delBeforePunctuation',
    handler(text) {
        return text
            .replace(/([!?]) (?=[!?])/g, '$1')
-            .replace(/(^|[^!?:;,.…]) ([!?:;,.])(?!\))/g, '$1$2');
+            .replace(/(^|[^!?:;,.…]) ([!?:;,.])(?![\)\d])/g, '$1$2');
    }
};
```

**Comment by hcodes** [comment]
Пришло время для отдельного правила для точки, похожая ситуация https://github.com/typograf/typograf/issues/312

**Comment by hcodes** [comment]
#384
