### ISSUE TITLE
Вложенные кавычки "Го"ра → «Го«ра

### ISSUE THREAD

**Issue by TITAN-UZ** [typograf/typograf#392]
Приветь как добавит условия для замену если текст без пробела до или после кавычек!

"Го"ра → «Го«ра 
Го"ра" → Го"ра»

**Comment by hcodes** [comment]
Правило для добавления пробелов у кавычек?

**Comment by TITAN-UZ** [comment]
В Узбекском кириллице ест дополнения слов в кавычек  например 
```
«Реал»га
«Аталанта»ни
«Барселона»нинг
```
которого нет в русском орфографии при типографии таких текстов при замени получается 
```
Мен туфайли "Барселона"нинг → Мен туфайли «Барселона"нинг
```
или не заменяет если вот так

`Мен туфайли"Барселона"нинг`
 
Как можно решит этих проблем в Узб кириллице

**Comment by hcodes** [comment]
Интересный случай, нужно доработать расстановку кавычек.
Похожая проблема: https://github.com/typograf/typograf/issues/379

**Comment by hcodes** [comment]
Будет учтено в https://github.com/typograf/typograf/issues/379
