### ISSUE TITLE
Пробел после запятой не всегда исправляется

### ISSUE THREAD

**Issue by MikeVL** [typograf/typograf#397]
Пример текста:
`Перечень приобретаемого:КОНДЕНСАТОРЫ КМ,К52-2,ЭТО-2,К10-47,МИКРОСХЕМЫ,ТРАНЗИСТОРЫ,РАЗЬЕМЫ,РЕОХОРДЫ И ПЕРЕКЛЮЧАТЕЛИ С ПРИБОРОВ КСМ,КСП,КСД,РП-160,ТЕРМОПАРЫ ТПП,ТПР,КОНТАКТЫ(СЕРЕБРО),ТИРИСТОРЫ И ДИОДЫ.`

Результат:
`Перечень приобретаемого: КОНДЕНСАТОРЫ КМ, К52-2,ЭТО-2,К10-47,МИКРОСХЕМЫ, ТРАНЗИСТОРЫ, РАЗЬЕМЫ, РЕОХОРДЫ И ПЕРЕКЛЮЧАТЕЛИ С ПРИБОРОВ КСМ, КСП, КСД, РП-160,ТЕРМОПАРЫ ТПП, ТПР, КОНТАКТЫ (СЕРЕБРО), ТИРИСТОРЫ И ДИОДЫ.`

**Comment by hcodes** [comment]
Спасибо за баг, проблема возникает из-за цифр в конце слова, нужно добавить дополнительную проверку.

**Comment by hcodes** [comment]
v6.14.0
