### ISSUE TITLE
Не исправляет пробел перед точкой

### ISSUE THREAD

**Issue by MikeVL** [typograf/typograf#401]
Вот пример текста:
`Куплю привода новые и с хранения .Предложения на почту или звоните по указанным телефонам.`
`Цены договорные.фото по запросу.`

Ещё такой вариант:
`4 комплекта 2014 г.в. фото по запросу.цена договорная.`
Исправляет так
`4 комплекта 2014 г. в. фото по запросу.цена договорная.`

**Comment by MikeVL** [comment]
Ещё обнаружил такую замену, что не праильно:
`Продам трансформаторы ТМН 4000/35/6 и ТМН 4000/35/10, 90-е гг.вв., капитальный ремонт, гарантия.`

Меняет на 
`Продам трансформаторы ТМН 4000/35/6 и ТМН 10.35.4000, 90-е гг. вв., капитальный ремонт, гарантия.`

Ещё вариант:
`Продам трансформатор ТМН 6300/35/10, 1990 г. в., кап.ремонт, гарантия. Цена 2,2 млн. р. с НДС. Торг.`

**Comment by hcodes** [comment]
> Вот пример текста: `Куплю привода новые и с хранения .Предложения на почту или звоните по указанным телефонам.` `Цены договорные.фото по запросу.`
> 
> Ещё такой вариант: `4 комплекта 2014 г.в. фото по запросу.цена договорная.` Исправляет так `4 комплекта 2014 г. в. фото по запросу.цена договорная.`

Раньше Типограф такие ошибки исправлял, но это вело к другим ошибкам.
Например: `Яндекс.Маркет`, `.45`, `.Net-разработчик`, `сайт.рф` и прочее.
