### ISSUE TITLE
Использовать Типограф в программах Better Touch Tool или Raycast

### ISSUE THREAD

**Issue by Khilkov** [typograf/typograf#408]
Всем привет! 
Заранее прошу прощения за глупый вопрос, но вдруг кто-то сможет помочь.Подскажите, пожалуйста, можно ли как-то использовать Типограф в программах Better Touch Tool или Raycast?

**Comment by hcodes** [comment]
Для `Better Touch Tool` можно воспользоваться [командным интерфейсом](https://github.com/typograf/typograf-cli) Типографа и через bash-скрипт использовать https://docs.folivora.ai/docs/8c_text_transformer_functions.html

**Comment by hcodes** [comment]
Для `Raycast` правильно было бы сделать полноценное расширение и положить в [Store](https://www.raycast.com/store).

**Comment by hcodes** [comment]
> Для `Raycast` правильно было бы сделать полноценное расширение и положить в [Store](https://www.raycast.com/store).

Ну или также использовать командный интерфейс.
