### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by dkrnl** [typograf/typograf#412]
after update to v6.15.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/typograf.js' is not defined by "exports" in ./node_modules/typograf/package.json

**Comment by mcler** [comment]
https://github.com/typograf/typograf/pull/413 Might resolve this issue

**Comment by hcodes** [comment]
v6.15.1
