### ISSUE TITLE
Предложение: Добавить новое api для итерации по массиву строк. 

### ISSUE THREAD

**Issue by lShinal** [typograf/typograf#416]
Описание проблемы:

Если итерировать по массиву строк то контекст типогрофа применяется отдельно для каждой строки.

Пример: 
```
import Typograf from 'typograf';

[`"`, 'привет', `".`].map((str) =>
    tp.execute(str),
);
```

Вывод:
`[ '"', 'привет', '«.' ]`

Пример использования:
```

tp.execute([`"`, 'привет', `".`]),

```

Ожидаемый вывод:

`[ '«', 'привет', '».' ]`

**Comment by hcodes** [comment]
Идея хорошая, но пока Типограф обрабатывает только по строкам.

**Comment by hcodes** [comment]
Сейчас Типограф обрабатывает HTML [по частям](https://github.com/typograf/typograf/blob/dev/src/main.ts#L98), это было сделано из-за ошибок с кавычками.

В новом предложении необходимо будет учитывать предыдущие символы (слова), на это не рассчитаны текущие правила. Плюс, возникнут пограничные случаи.

Почему просто не собрать строку? Нужен вариант использования.
```js
tp.execute([`"`, 'привет', `".`].join(''));
```

**Comment by lShinal** [comment]
@hcodes В моём личном случае я собираю массив строк из JSON из объектов текстовых нод. Которые я хочу типографировать. Я пробовал решить это склеиванием в одну строку текста, но появлялась проблема обратного разбиения в массив. В общем, я решил эту проблему, склеивая строки не пустой строкой, а специальным символом и удалением его после типографирования.
