### ISSUE TITLE
Поддержка markdown

### ISSUE THREAD

**Issue by hcodes** [typograf/typograf#43]

**Comment by mkpankov** [comment]
О, я был бы очень рад этой возможности. Хочу типографировать публикации в блоке на `jekyll`, и без разбора хотя бы front matter и code blocks далеко не уедешь.

**Comment by hcodes** [comment]
Да, нужно сделать разбор Markdown на AST и потом типографировать.

**Comment by hcodes** [comment]
Issue уже больше года, в ближайшее время поддержки Markdown не будет.

**Comment by pepelsbey** [comment]
Может быть пора открыть ишью и всё-таки сделать поддержку маркдауна? Годы идут, а потребность никуда не уходит — только становится больше.

**Comment by hcodes** [comment]
Переоткрыл, надеюсь доберусь, если появится время или кто-нибудь поможет.

**Comment by pepelsbey** [comment]
Ура! Готов тестировать, снабжать идеями и всячески участвовать :)

**Comment by Mavrin** [comment]
Написал [плагин](https://github.com/Mavrin/remark-typograf) к  [remark](https://github.com/remarkjs/remark)

**Comment by hcodes** [comment]
Спасибо, добавил плагин в README.

**Comment by hcodes** [comment]
Прошло 8 лет с заведения задачи, дольше ждать не стоит. Задачу закрываю и добавляю тег «delayed», возможно, вернусь к ней когда-нибудь :)

**Comment by ceigh** [comment]
Мой [плагин](https://github.com/ceigh/markdown-it-typograf) для [markdown-it](https://github.com/markdown-it/markdown-it) 😇.

**Comment by hcodes** [comment]
> Мой [плагин](https://github.com/ceigh/markdown-it-typograf) для [markdown-it](https://github.com/markdown-it/markdown-it) 😇.

Спасибо! Добавил в README.

**Comment by OnkelTem** [comment]
Всем привет!

Начал пользоваться в VSCode для README файлов и статей, и приходится выделять по параграфам и проверять не сбился ли Markdown.

Например, во фразе: `**Какой закон формальной логики нарушен?**` будет поставлен неразрывный пробел после знака вопроса, что ломает MD, так как до `**` не должно быть неразрывных пробелов.

Другой пример, ломаются списки, так как маркер списка — дефис — заменяется на длинное тире.

Мне кажется в наше время MD это вообще основной формат и обходить его стороной — это некоторое упущение.

P.S. А есть ли правила, которые можно как конфиг применить, чтобы более safe было натравливать на MD?

**Comment by Mavrin** [comment]
https://github.com/Mavrin/remark-typograf Это плагин не вставляет неразрывный пробел после знака вопроса.
