### ISSUE TITLE
Лишние пробелы после точки с запятой

### ISSUE THREAD

**Issue by Seag011** [typograf/typograf#432]
Правило 'common/space/afterSemicolon' добавляет пробел при использовании HTML Entity.
Например: 
`<p>Слово&nbsp;для примера</p>`
вернёт следующее:
`<p>Слово  для примера</p>`
И к символу добавляется лишний пробел.

**Comment by hcodes** [comment]
1. Какая версия Типографа используется?
2. Какие дополнительно включены правила?

@Seag011

**Comment by Seag011** [comment]
1. 7.0.0
2. 
```
Typograf.addRule({
      name: 'ru/afterNumberSignWhitespace',
      queue: 'end',
      handler(text) {
          return text.replace(/№\s*(\S)/g, '№&nbsp;$1');
      }
});
```

Проблема пофиксилась при добавлении  `queue: 'end'` к параметрам правила.
Есть ли возможность добавить подробности про очереди обработки в документацию?

**Comment by hcodes** [comment]
Типограф работает с чистым UTF-8 внутри правил, HTML-сущности использовать не нужно. Или только в редких случаях, указывая `queue: 'end'`.

```
Typograf.addRule({
      name: 'ru/afterNumberSignWhitespace',
      handler(text) {
          return text.replace(/№\s*(\S)/g, '№\u00A0$1');
      }
});
```
P.S.: Спасибо, этот момент допишу в документацию.
