### ISSUE TITLE
Привязка инициалов к фамилии внутри круглых скобок

### ISSUE THREAD

**Issue by alex-petrakov** [typograf/typograf#434]
Кажется, что расстановка неразрывных пробелов между инициалами и фамилией не срабатывает, если вся конструкция заключена в круглые скобки. Пример:

```
Исходный текст      Ожидается           Фактический результат
(М. Ю. Лермонтов)   (М._Ю._Лермонтов)   (М. Ю. Лермонтов)
```

Такой вариант употребления инициалов и фамилии может встретиться при указании на автора цитаты, например:

> Со мною был чугунный чайник — единственная отрада моя в путешествиях по Кавказу (М. Ю. Лермонтов).

Наверное, случай с открывающей скобкой перед инициалами можно было бы учитывать аналогично случаю с открывающей кавычкой.

P. S. Спасибо за отличный инструмент.

**Comment by hcodes** [comment]
https://github.com/typograf/typograf/pull/443
