### ISSUE TITLE
Опция: короткое тире вместо длинного / Option: en-dash instead of em-dash

### ISSUE THREAD

**Issue by onsamyj** [typograf/typograf#438]
Заметил, что англоговорящие скрин-ридеры не понимают длинное тире, просто его проскакивают, что усложняет понимание текста. Можно ли в настройке замены дефиса на тире добавить выбор на какое именно тире?

I noticed that screen readers don’t understand em-dashes and just skip them, which makes the text less coherent. Can we have the option to choose which dash to use in the replacement setting?

**Comment by hcodes** [comment]
Можно добавить своё правило и заменять на необходимые дефисы.
@onsamyj
