### ISSUE TITLE
заменять «тыс.» на «000»

### ISSUE THREAD

**Issue by unxed** [typograf/typograf#446]
Потому что «тыс.» на один знак БОЛЬШЕ, чем 000. Бессмысленный канцелярит.

**Comment by unxed** [comment]
Канцелярит вроде «1 миллион 541 тысячу» тоже хорошо бы во что-то адекватное превращать. Увы, и такое иногда пишут.

**Comment by denis-bosiy** [comment]
Иногда сокращения чисел пишут, подразумевая то, что числа округлены.
К примеру, в таблицах присутствуют значения, которые необходимо сравнить. Удобно их привести к одному и тому же порядку, округлив их, а также записав порядок в виде сокращения.

Если же менять сокращение на числа, то теряется «коннотация» округления.

**Comment by hcodes** [comment]
Для этого случая можно написать [своё правило](https://github.com/typograf/typograf/blob/dev/docs/api_rules.md#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B5-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE).
