### ISSUE TITLE
Webkit browsers error: Something went wrong. SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by neosheps** [typograf/typograf#450]
Использовал вашу либу в SPA приложении на React + vite. Проблема возникает на моб. устройствах эппл после того, как я добавил lazy-loading и Suspense обертку к компоненту с текстом

Увидел, что последний коммит, затрагивающий регулярки, это вот: https://github.com/typograf/typograf/commit/0fa96753ae136c88f40ffdafd82e8745347247f0

Откатился до версии 4.1, всё стало ок, пишу FYI

**Comment by hcodes** [comment]
Спасибо, воспроизвёл ошибку, [детали](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group).

**Comment by hcodes** [comment]
Рабочая версия (без бага) 7.3.0, не 4.1.

**Comment by SeMech** [comment]
Мне помог переход на 6.9.0
На 7.3.0 воспроизводится баг

Проект на next, версия 14.2.3

**Comment by hcodes** [comment]
Откатил #447. 
v4.7.1
