### ISSUE TITLE
Catastrophic Backtracking в правиле "ru/punctuation/quot"

### ISSUE THREAD

**Issue by Bahus** [typograf/typograf#78]
Насколько я понимаю некорректное регулярное выражение для тегов приводит к зависанию типографа на определенных текстах.

Вот так сейчас выглядит [регулярка для тега](https://github.com/typograf/typograf/blob/dev/dist/typograf.js#L1446):

```js
var tag = '(?:^|<\\w.*?>)*';
```

Из-за того, что здесь `.` включает в себя символ `>` итоговая регулярка на текстах с большим количеством тегов подряд вешает браузер, вот тут пример таймаута для итоговой регулярки: https://www.regex101.com/r/bM5yU9/2

Исправление на корректное выражение данную проблему "лечит" (тесты не прогонял):

```js
var tag = '(?:^|<\\w[^>]*?>)*';
```

**P.S.** Я бы еще `^` вынес из этого выражения, оно больше подходит для итогового.

**Comment by hcodes** [comment]
Перед выполнением правил все теги экранируются специальным образом, чтобы "не мешать" в правилах. Это тяжелая операция, т.к. на каждый тег вызывается функция. Постараюсь оптимизировать данный случай.
 
Правило с кавычками нужно переделать, т.к. оно писалось в самом начале разработки типографа (многое поменялось).
`var tag` там уже не нужен, т.к. теги уже экранируются.
Начал переписывать #79, ускорение в несколько раз.

**Comment by hcodes** [comment]
Поправил, выпустил новую версию.
