### ISSUE TITLE
Добавить исключение: про то

### ISSUE THREAD

**Issue by sergeevabc** [typograf/typograf#83]
Ожидаешь:
```Они показывают фильмы про то, как люди играют «играют в салочки» в концлагерях.```

Получаешь:
```Они показывают фильмы про-то, как люди играют «играют в салочки» в концлагерях.```

Пока приходится отключать правило «дефис перед то, либо, нибудь, ка, де, кась».

**Comment by hcodes** [comment]
Скорее всего, придется разделить на несколько правил и добавить исключения.
http://www.gramota.ru/class/coach/tbgramota/45_122

**Comment by sergeevabc** [comment]
Спасибо, Денис.
