### ISSUE TITLE
Минификация ломает типографинг html-тегов

### ISSUE THREAD

**Issue by kojoru** [typograf/typograf#85]
Как воспроизвести:
1) скачать из bower типограф и подключить 
```
   <script src="bower_components/typograf/dist/typograf.min.js"></script>
```
2)     Запустить код:
```
    var tp = new Typograf({lang: 'ru'});
    alert(tp.execute('     <p>Мир - мой мир!</p>      '));
```

Ожидаемый результат: `<p>Мир — мой мир!</p>`
Полученный результат: `<?>tf0<?>Мир — мой мир!<?>tf1<?>`

Если подключать неминифицированную версию, всё работает как ожидалось.

**Comment by hcodes** [comment]
Проблема решилась добавлением опции в `uglify` - `output: {ascii_only: true}`.
