### ISSUE TITLE
Проблема с минимизацией через uglify

### ISSUE THREAD

**Issue by KhodeN** [typograf/typograf#95]
Ваша библиотека - одна из многих, использующихся в проекте.
Весь проект собирается в один файл и жмется с помощью uglifyjs.
После этого, если в тексте были теги, то они обратно не превращаются и в тексте остаются артефакты типа `�tf1�`. 
Думаю, косяк возникает в функции _showSafeTags. После минимизации она выглядит так:

```javascript
    _getPrivateLabel: function(i) {
        return "�tf" + i + "�";
    },
...
    _showSafeTags: function(text) {
        for (var i = 0; i < this._safeTags.length; i++) {
            text = text.replace(/\uDBFFtf\d+\uDBFF/g, this._replaceLabel.bind(this));
            if (text.search(/\uDBFFtf\d/) === -1) {
                break;
            }
        }
        delete this._hiddenSafeTags;
        return text;
    },
```
и, почему-то, не работает.

**Comment by hcodes** [comment]
Такая проблема уже была #85, решилась `uglify` - output: `{ascii_only: true}`.
Специально выбрал частный диапазон символов в UTF-8, чтобы не было конфликтов.
Наверное, следует указать в документации про этот случай.

**Comment by KhodeN** [comment]
Думаю, да, стоит указать. А то я, к примеру, убил часа два, чтобы понять, что именно не так с минимизацией. Надо было сразу глянуть в `gulpfile.js`

**Comment by hcodes** [comment]
Можно исключение ещё кидать в js, случай частый.

**Comment by hcodes** [comment]
Добавил в README.
