### ISSUE TITLE
Портятся URL

### ISSUE THREAD

**Issue by KhodeN** [typograf/typograf#97]
Если в тексте есть URL, то они не превращаются в ссылки (при включенной настройке).
Вместо этого они ломаются.

`пошли письмо на http://ya.ru/` -> `пошли письмо на http: //ya.ru/`

https://typograf.github.io/#!text=%D0%BF%D0%BE%D1%88%D0%BB%D0%B8%20%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%BE%20%D0%BD%D0%B0%20http%3A%2F%2Fya.ru%2F

**Comment by hcodes** [comment]
Да, проблема в правиле «Пробел после знаков пунктуации».

**Comment by hcodes** [comment]
v2.10.0

**Comment by lgordey** [comment]
Ломает ссылки из-за того же правила, но теперь после вопросительного знака.

`https://www.youtube.com/watch?v=C0DPdy98e4c` 
=>
`https://www.youtube.com/watch? v=C0DPdy98e4c`

**Comment by lgordey** [comment]
Также ломает даты в ссылках из-за [ru/date/fromISO](https://github.com/typograf/typograf/blob/dev/src/rules/ru/date/fromISO.js).

`https://lenta.ru/news/2016/04/12/notes/`
=>
`https://lenta.ru/news/12.04.2016/notes/`

**Comment by hcodes** [comment]
Завёл баг #151
